<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimal Sisa Cuti_max_carry_forward</name>
   <tag></tag>
   <elementGuidId>26a5d7df-2bcc-4441-9db7-5f85e831e3e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max_carry_forward</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_carry_forward']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Maksimal Sisa Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6027ae12-e3e3-490d-9719-88f81859a516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>31479764-a491-4ccd-b0a2-dd3b2fd3f617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>1c21ab43-297d-4545-a88a-6c1f5f8a211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>7d3f6c52-9a9e-4fb9-9f48-d9c4045b5c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maksimal Sisa Cuti</value>
      <webElementGuid>c55d0786-72a6-4c6c-a83b-a5a05a4d813d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d2068428-d796-4d05-9a6e-98ca633c95e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>35187f2f-0fa7-4a64-9df4-2ed2a98fe0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25fc89c8-8aaa-4ac3-863f-c30bbb78beab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_carry_forward&quot;)</value>
      <webElementGuid>1291ee04-7ebe-49ff-abc1-3584d07c8d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_carry_forward']</value>
      <webElementGuid>4b0552e8-ff78-4242-857b-39647c7a4d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>8a822b38-e0ba-4ff3-bc7d-421b5e05c334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_carry_forward' and @name = 'max_carry_forward' and @placeholder = 'Maksimal Sisa Cuti' and @type = 'number']</value>
      <webElementGuid>4af471ee-bdcc-4382-ba9e-fde204cf41e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
