<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Bulan Kerja Sisa Cuti_carry_fo_08b2bb</name>
   <tag></tag>
   <elementGuidId>d9a4292d-27b3-4016-a1bd-d0be9dc7bcd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carry_forward_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='carry_forward_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Jumlah Bulan Kerja Sisa Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d422a28-3ab8-4fa2-827b-ee79f2b6ad72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1e3bc8a-e43a-4b25-93c5-66ad412518ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>2d6b8097-5fd5-46ab-824e-76ef4c15d37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>3906b7f2-b693-4f5a-951d-7b88886bd39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Bulan Kerja Sisa Cuti</value>
      <webElementGuid>ae88dda6-b04a-4fa4-a0fb-98ca5221e190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e3bd9b78-ee7a-4c40-bcfd-4b978b2110ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>82521708-e200-4106-bcc0-da644e02030e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6510709e-0d23-4eaf-b119-ef2b66e14866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carry_forward_total_month&quot;)</value>
      <webElementGuid>d008570c-43ad-4f1d-ad68-e8b8c1c9e55a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='carry_forward_total_month']</value>
      <webElementGuid>d38205f9-bb68-4803-b5a6-c293152176e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>cf88bd0d-08a4-44f6-9415-072edd79c3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'carry_forward_total_month' and @name = 'carry_forward_total_month' and @placeholder = 'Jumlah Bulan Kerja Sisa Cuti' and @type = 'number']</value>
      <webElementGuid>87be691a-d401-4b2d-937f-fde938d8b58d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
