<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eligible Pengaturan Cuti (Bulan)_elig_9860f4</name>
   <tag></tag>
   <elementGuidId>52bbba97-20d9-4fb8-8bb1-96bdb16abb1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eligible_leave_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eligible_leave_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Eligible Pengaturan Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bd264dc-d99a-4720-aed9-ec1162aec9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa36e6ac-dc6f-4fe5-9d7a-be64d43cb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>2b0edccb-5ec5-42b8-9721-a98daa7ecd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>6b0ee5b0-6365-4af3-b26a-4da2c61fa5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eligible Pengaturan Cuti</value>
      <webElementGuid>b6f6144b-014b-4ad6-97e1-6663c3f3c0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9ff24a71-dd24-4718-be94-e529a6846246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>0255c663-ad8a-4c49-bab9-1b1e4733b0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ded0e7f-be9b-4580-a26f-52022c611151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eligible_leave_total_month&quot;)</value>
      <webElementGuid>2f314cbf-b653-4ee2-9132-beb199ccff4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eligible_leave_total_month']</value>
      <webElementGuid>5b8ed615-cc8a-4fab-92f1-cb6a8ca77b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/input</value>
      <webElementGuid>77a08674-56c8-4eb2-b9d4-41657dbb2fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eligible_leave_total_month' and @name = 'eligible_leave_total_month' and @placeholder = 'Eligible Pengaturan Cuti' and @type = 'number']</value>
      <webElementGuid>9ad1f8da-1627-407c-847a-3f394a0fafa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
