<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Maksimal Sisa Cuti_field</name>
   <tag></tag>
   <elementGuidId>26a5d7df-2bcc-4441-9db7-5f85e831e3e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max_carry_forward</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_carry_forward']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Maksimal Sisa Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57ac271d-bf10-4fd0-a823-bbb56c773ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04491dd7-bc32-44c1-a0c2-4f26574b5228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>6cb67527-8523-403c-9f78-586fe7758088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>23f4a191-700d-4102-8a2b-3f84fbba1033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maksimal Sisa Cuti</value>
      <webElementGuid>4fe06453-d960-4432-be21-f2b31f993213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3cdb1c8f-2636-45cc-8299-373b2f22b384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>979495d0-d874-4146-9d10-790cd2a1ddf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1050649-82d0-4c72-8849-171b6a73bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_carry_forward&quot;)</value>
      <webElementGuid>2c54126a-aeb5-4b0f-8260-02231243c563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_carry_forward']</value>
      <webElementGuid>c7206b1b-72f3-4a13-8f81-60076b6d19ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>72dd8daa-7014-47dd-8829-a7529b10a049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_carry_forward' and @name = 'max_carry_forward' and @placeholder = 'Maksimal Sisa Cuti' and @type = 'number']</value>
      <webElementGuid>8f9a214a-1e7d-4fa2-9baa-19953a783410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
