<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Bulan Kerja Sisa Cuti_carry_fo_08b2bb</name>
   <tag></tag>
   <elementGuidId>43a53370-2f2d-4324-b84e-f5d3ed90479e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carry_forward_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='carry_forward_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Jumlah Bulan Kerja Sisa Cuti...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f027a20-a691-4e0a-bfd2-88cfbad23892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8722fba0-b0ce-4567-aceb-ba8ec9e9187b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>97deb694-c2f5-40a6-8b31-03652821de16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>955d00a0-f04d-4148-8df2-e4731bc7733b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Bulan Kerja Sisa Cuti...</value>
      <webElementGuid>a153bcc2-12d9-44fc-890d-dbf3f8cdb658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c010b01e-fb3e-4659-823d-b1755ae08b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>debf5342-9beb-49b6-b02b-aaa137eb6457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8138168f-0e0f-49da-b884-d3e4437b266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carry_forward_total_month&quot;)</value>
      <webElementGuid>5dbd2278-27cf-4752-b0b7-8e2c69d700a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='carry_forward_total_month']</value>
      <webElementGuid>3813b2e4-30a3-41e5-94cf-8d3c615ae7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>3c170815-2901-439a-9646-08f27f713228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'carry_forward_total_month' and @name = 'carry_forward_total_month' and @placeholder = 'Jumlah Bulan Kerja Sisa Cuti...' and @type = 'text']</value>
      <webElementGuid>0325ce5d-ee82-4523-ab85-3094ccb0eb20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
