<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>e71590f7-188d-4a7e-a6ee-b70a71081162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Cuti&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[5]/div/div/a/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>46861040-bbd0-473a-a4da-b18bdb12757b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cuti</value>
      <webElementGuid>4a1241a2-4be2-4d96-9dbb-1e741daf417d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>8a6fc520-0405-44d3-b59e-a3075b871dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=640&amp;q=75 640w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=750&amp;q=75 750w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=828&amp;q=75 828w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>e49bcf25-afef-4f49-84b1-dee7def0580e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=3840&amp;q=75</value>
      <webElementGuid>2f4eaaeb-d5be-41ac-be25-8cc20051773b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>550de66c-4caf-4b51-b4f0-e6db87e1b29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>responsive</value>
      <webElementGuid>7f85ec93-bf07-466a-81c1-9ab2be143f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthSm css-ewqxmf&quot;]/div[@class=&quot;MuiBox-root css-19n8dai&quot;]/div[@class=&quot;MuiBox-root css-wmurvm&quot;]/div[@class=&quot;MuiBox-root css-1dovkig&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-3 MuiGrid-grid-sm-3 css-4xkoi8&quot;]/div[@class=&quot;MuiBox-root css-7wh13m&quot;]/div[@class=&quot;MuiBox-root css-zg1vud&quot;]/a[@class=&quot;user__menu__item&quot;]/div[@class=&quot;MuiBox-root css-11uwjng&quot;]/span[1]/img[1]</value>
      <webElementGuid>38efb9fe-bc0e-47db-bab0-7870d65ece29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[5]/div/div/a/div/span/img</value>
      <webElementGuid>9b4a8aad-05b0-441f-96c2-682e033b3cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cuti']</value>
      <webElementGuid>ae5625f0-99e4-49c4-817d-01047bcfcc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a/div/span/img</value>
      <webElementGuid>c6faea7a-94a8-4cb8-9512-ccc6f80f0233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cuti' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fleave.svg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>9c1898e9-36eb-4338-b8d7-76a84d62f9d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
