<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Tipe Cuti  Cuti berduka saudara kandungke_7ca2c5</name>
   <tag></tag>
   <elementGuidId>91a8e67c-db80-429f-824c-135b8cf050db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div[2]/div/div/div/div/div/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4b7f718f-0a54-4748-8762-e7b1321a65dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-y6r9ax</value>
      <webElementGuid>de9a2b05-93ca-4198-b624-128a8ec0649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipe Cuti : Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)</value>
      <webElementGuid>cfd4ccb1-29b0-4422-9e06-c6ef25beb5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthSm css-1cd81x&quot;]/div[@class=&quot;MuiBox-root css-1ejni00&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-178yklu&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1v6pvd8&quot;]/div[@class=&quot;MuiCardContent-root css-kiy27h&quot;]/div[@class=&quot;MuiBox-root css-8atqhb&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-y6r9ax&quot;]</value>
      <webElementGuid>5ff54297-9415-4a18-99d1-41dd9b7d2c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div[2]/div/div/div/div/div/p[4]</value>
      <webElementGuid>a5610f55-e5c9-4bf0-b99f-24d5b434ec71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tipe Cuti :']/parent::*</value>
      <webElementGuid>b3fae8a3-d1a9-4219-8b3b-f894aecf716d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>299ed44b-6db0-4e15-99a2-05a1915a752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Tipe Cuti : Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)' or . = 'Tipe Cuti : Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)')]</value>
      <webElementGuid>fb738e0a-f76c-44a2-825c-e401d5101a1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
