<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_level Jabatan_level</name>
   <tag></tag>
   <elementGuidId>8435d509-1e7a-48d5-bed7-37cfc998fde3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#level</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='level']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c708229d-01a6-46d8-9e6a-690f28b5291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17d63531-91e9-4bcb-978d-2a5e76e1e555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>level</value>
      <webElementGuid>dd915b6b-0e3c-48d9-9833-907e5d842597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>level</value>
      <webElementGuid>089a7d45-3e1c-4dde-8f8a-ce191311d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0ca5c01b-6887-4e41-b60e-297ddbbc6f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5db8fbb-ddb0-4222-a4b6-2b2f5c4a2143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>6d731aee-9cd9-494f-a039-272c56f5ba52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level&quot;)</value>
      <webElementGuid>32eae6ec-211c-4f33-931d-e37722ded8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='level']</value>
      <webElementGuid>44943162-527e-47a0-a6aa-60a99a502863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-slide-description']/div[2]/div/input</value>
      <webElementGuid>2e72b371-9972-4ff7-93cc-86a6ec545ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>77004a7c-4652-48c9-bf75-77f57cf68992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'level' and @name = 'level' and @placeholder = '100' and @type = 'text']</value>
      <webElementGuid>8178b4a8-d658-4847-8f85-fe7d29d63add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
