<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimal Sisa Cuti_max_carry_forward</name>
   <tag></tag>
   <elementGuidId>9e6ea417-027f-4cbf-b50f-a111d05c3cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max_carry_forward</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_carry_forward']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Maksimal Sisa Cuti...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dccaedf-a45e-4609-a06a-c1ac99fdb956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd41939f-4e19-4d34-841e-21ff1b4b02f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>77383775-d38f-4bd5-8a88-e5c336984954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>5f6747f9-f5fd-4a01-b756-59bbd0402293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maksimal Sisa Cuti...</value>
      <webElementGuid>66a7f60c-145a-4851-ba3f-403897b084e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79b3bfd3-9b75-4660-b408-0d09c938496f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>147210f3-cb53-4c31-b54b-1080c55fa3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4d9fd269-d09f-452b-9491-c1eeee19179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_carry_forward&quot;)</value>
      <webElementGuid>b6d0041b-8152-4fa8-bf92-602d71f601ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_carry_forward']</value>
      <webElementGuid>d0c9f8df-6f6a-4490-bd18-c65da23f2704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>244e7e47-b9b5-4302-b904-97558571e36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_carry_forward' and @name = 'max_carry_forward' and @placeholder = 'Maksimal Sisa Cuti...' and @type = 'text']</value>
      <webElementGuid>a06440e9-5b5b-46e4-a50a-1e2bfb3b3af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
