<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Bulan Kerja Sisa Cuti_carry_fo_08b2bb</name>
   <tag></tag>
   <elementGuidId>43a53370-2f2d-4324-b84e-f5d3ed90479e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carry_forward_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='carry_forward_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Jumlah Bulan Kerja Sisa Cuti...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0d5fa25-3916-4aa0-a68b-fbd3eba10de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46ac8e7d-16f4-4612-b9d3-c0afacbb6bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>5915fb80-78f0-4f45-afee-a493b9258a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>711ef8e1-eb4b-4674-9545-3adef5f83123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Bulan Kerja Sisa Cuti...</value>
      <webElementGuid>58192fb0-18c7-4b61-97d6-83c218780507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13a91b89-b41c-4ef7-94de-4d62478a786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>9b1b3917-2aef-4118-b6ea-e2d010a84531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f8befdea-6764-44b2-975b-2a24bd5e9a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carry_forward_total_month&quot;)</value>
      <webElementGuid>da6e525f-fe15-4c7c-a9fd-fdc7374e248b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='carry_forward_total_month']</value>
      <webElementGuid>9f8ee3bc-3bba-437c-baab-81dccaf16d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>f5275617-eed8-40a4-8e89-e43e0706c0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'carry_forward_total_month' and @name = 'carry_forward_total_month' and @placeholder = 'Jumlah Bulan Kerja Sisa Cuti...' and @type = 'text']</value>
      <webElementGuid>e4891a6e-0c4d-455c-8dd1-afb69eaabe34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
