<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eligible Pengaturan Cuti (Bulan)_elig_9860f4</name>
   <tag></tag>
   <elementGuidId>4ebfe1cd-1c01-4b17-bb62-58d98a15ce27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eligible_leave_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eligible_leave_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Eligible Pengaturan Cuti...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce26afb-2c25-4167-ac34-4d22085f330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4af54b1-a7a8-43c4-90d8-6bf0303ba1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>f58af1f3-854a-4ba5-a99c-2ab1eb02d92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>cf3a20c5-c890-4d02-a446-76bbbbeb277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eligible Pengaturan Cuti...</value>
      <webElementGuid>24feb430-bbb4-4894-ab49-c208d0a7ac5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d433df0-f666-48fb-aac0-181d9567ed06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>56cb3866-ad9c-4b77-9315-3a7835f0a84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02d8ba6a-a85f-440e-b7b4-74a2eefa9ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eligible_leave_total_month&quot;)</value>
      <webElementGuid>47d5d50c-0e1f-4202-af93-ee3148da4dcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eligible_leave_total_month']</value>
      <webElementGuid>4f7a3530-9910-4c2e-8e92-d1bb7f0a4b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/input</value>
      <webElementGuid>514a1517-0dd1-460e-b069-6b005abb331d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eligible_leave_total_month' and @name = 'eligible_leave_total_month' and @placeholder = 'Eligible Pengaturan Cuti...' and @type = 'text']</value>
      <webElementGuid>78e11390-1291-4d9c-a732-dd4e3ef23e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
