<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eligible Pengaturan Cuti (Bulan)_elig_9860f4</name>
   <tag></tag>
   <elementGuidId>4ebfe1cd-1c01-4b17-bb62-58d98a15ce27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eligible_leave_total_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eligible_leave_total_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Eligible Pengaturan Cuti...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41093309-0952-40b5-8f8b-25de6e98d4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b23bba83-5b78-4dfb-8fc1-6f6b49a7bf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>72f74f88-a805-4a9c-bb33-961f6879fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>b9f22bed-a828-48d5-b4d1-03b38da6c485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eligible Pengaturan Cuti...</value>
      <webElementGuid>1f3dea3c-c70d-4dbf-b843-6bd757f04717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39ff25ba-8dcd-4d79-a22c-f76bb990780b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>b776f32e-115c-4d89-9600-9392f21583f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef03893e-4b0f-4246-a138-3fa4cec1a8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eligible_leave_total_month&quot;)</value>
      <webElementGuid>27c29631-1828-4c77-98b1-5807a1a49761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eligible_leave_total_month']</value>
      <webElementGuid>372140f7-080a-4819-8519-77bc81ced0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/input</value>
      <webElementGuid>dec1f3ad-da21-49c6-8436-0c80e5987773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eligible_leave_total_month' and @name = 'eligible_leave_total_month' and @placeholder = 'Eligible Pengaturan Cuti...' and @type = 'text']</value>
      <webElementGuid>d8ba29d9-af77-4865-928e-9b7c1f5961a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
