<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Tambah Data Jadwal</name>
   <tag></tag>
   <elementGuidId>e0007dcf-c173-4dd1-a254-d28112521e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-dialog-slide-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='alert-dialog-slide-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>336e217e-c895-4f3a-ae28-f12f7152154e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h4 MuiDialogTitle-root css-3fsi6u</value>
      <webElementGuid>2628f5b7-1e39-4b99-8da1-fd5c46683d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-dialog-slide-title</value>
      <webElementGuid>2772ebe7-8e03-4760-94b8-0691bbe438c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Data Jadwal</value>
      <webElementGuid>12c5036d-364f-41e7-9242-3d7f444cc66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-dialog-slide-title&quot;)</value>
      <webElementGuid>15ee99bf-6689-4167-819c-856f9c5bf700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='alert-dialog-slide-title']</value>
      <webElementGuid>11922175-3922-4efb-8b02-04001443e0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/following::h2[1]</value>
      <webElementGuid>6fbaabb3-4788-48fc-a46f-eb2d8267373c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[10]/following::h2[1]</value>
      <webElementGuid>5a5326a7-b260-45ac-a7bf-f3269af30a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::h2[1]</value>
      <webElementGuid>60336838-1023-4a9a-9bb4-d1f1bbabd759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Data Jadwal']/parent::*</value>
      <webElementGuid>df53ad23-e38d-4751-acfc-6d5fd04f7d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>98f499cb-b345-4972-9779-2540ba3d4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'alert-dialog-slide-title' and (text() = 'Tambah Data Jadwal' or . = 'Tambah Data Jadwal')]</value>
      <webElementGuid>edbc72c4-cebb-4abb-9493-bf47cf18d5c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
