<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaJadwal</name>
   <tag></tag>
   <elementGuidId>32369562-73f4-4544-896f-c1e79bbcbb46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameJadwal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameJadwal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7aa2159-124b-40a0-a2eb-bbcd21128eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9442b66-f337-4653-93df-42fbef7b1d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameJadwal</value>
      <webElementGuid>b2d972f7-6afa-4fee-9ec5-a74bf532d0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameJadwal</value>
      <webElementGuid>61abf12b-d843-46fc-a1ef-12451aa516ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfbacfa6-b3fb-4ce8-9616-2c8eb1e58471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>aa4cd886-a25f-4bfa-9d30-629538b8c2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameJadwal&quot;)</value>
      <webElementGuid>efa62ca4-f01c-4ec4-9916-5588b3b0af7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameJadwal']</value>
      <webElementGuid>2500cf25-f334-42f8-9869-3bf29e89a59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-dialog-slide-description']/div[2]/div/input</value>
      <webElementGuid>e6a93b14-df1d-4ced-8698-dd6af828d3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>168ccaea-699e-44ff-928c-8a01669dee14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nameJadwal' and @name = 'nameJadwal' and @type = 'text']</value>
      <webElementGuid>258f19ba-77a9-43d4-b441-636ae191a94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
