<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ToleransiKeterlambatan</name>
   <tag></tag>
   <elementGuidId>ea739225-a712-4912-becc-6400e3ce8530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_keterlambatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='t_keterlambatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc437167-dcf6-46b9-a5d8-5b2a41b23d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0669d8f2-519a-4c60-b194-91793b2ac556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t_keterlambatan</value>
      <webElementGuid>c2d49b03-13c6-4bb4-9e02-6e66d3c6a908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>t_keterlambatan</value>
      <webElementGuid>4f50f46b-08a4-4df3-84ae-e0ce066adf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0ba10ffb-de0a-4e6c-ad7c-a97278556da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>9e08faf9-582f-423f-9610-e5eae7596d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_keterlambatan&quot;)</value>
      <webElementGuid>7ab4c674-1271-48ef-831e-911b5aea60b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='t_keterlambatan']</value>
      <webElementGuid>eda65160-c2c1-4cc9-8181-6bd10a0b84d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-dialog-slide-description']/div[4]/div/input</value>
      <webElementGuid>26e23193-4051-483b-8da1-f8e61dc2fd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>60bb92ec-1f32-49fc-87c2-077bfd20c743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 't_keterlambatan' and @name = 't_keterlambatan' and @type = 'number']</value>
      <webElementGuid>36dc23ff-d722-4384-951e-4221f7e049c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
