<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Tambah Location Point</name>
   <tag></tag>
   <elementGuidId>e36ec392-503b-446a-8639-03cea3accbe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-dialog-slide-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='alert-dialog-slide-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b22dcfe8-a499-43d5-ace0-efe4300079b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h4 MuiDialogTitle-root css-3fsi6u</value>
      <webElementGuid>c125cdb2-4b59-41bc-9ec2-afe536103d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-dialog-slide-title</value>
      <webElementGuid>f90c9e6d-54d8-4096-bce4-ce783e6b3c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Location Point</value>
      <webElementGuid>36171e00-7963-488c-b59f-1afdf874873f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-dialog-slide-title&quot;)</value>
      <webElementGuid>ff3107df-8bc9-4797-9805-076c8104653d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='alert-dialog-slide-title']</value>
      <webElementGuid>718c7ed2-62f5-4134-9629-c6ad2421a168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/following::h2[1]</value>
      <webElementGuid>08ed0a34-f4aa-4c1c-9b29-c6bd3d0eacc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[10]/following::h2[1]</value>
      <webElementGuid>a61bc647-1343-48ea-9bae-565dcb26378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::h2[1]</value>
      <webElementGuid>1935fa54-d52d-4d0d-a48f-50d124ea4f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::h2[1]</value>
      <webElementGuid>61ffb2e4-43c7-4984-8334-3b34df4269e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Location Point']/parent::*</value>
      <webElementGuid>2ce7b567-b567-450f-96a9-31d74036d677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2c6f63b4-cf15-4d12-823a-76c4b6b91bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'alert-dialog-slide-title' and (text() = 'Tambah Location Point' or . = 'Tambah Location Point')]</value>
      <webElementGuid>4129a04e-e51e-4d24-9d67-120faf0a6572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
