<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>1aedfa25-408e-4e32-b148-ceb9aa2e8d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>line</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;menu&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>45b3186a-8b20-4ec8-8043-f6e67e351c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2ef69c04-f1ce-4883-bb71-b636cac3ad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>68873af7-67f5-42ce-b717-a11af85f1c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>03ce2020-29b8-4365-8797-9ba05c2545f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>06916205-0fdf-4d9f-b581-b9bcb8bcd67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-10f63sf&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed css-12q0zzl&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-5l32a9&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-sizeLarge css-17vpiyo&quot;]/svg[@class=&quot;feather feather-menu&quot;]/g[1]/line[1]</value>
      <webElementGuid>b33c68c5-7ae6-48c7-bae1-4bc32616dc51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
