<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>12e98f25-117d-4c63-9181-e144c2a3324f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>line:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;menu&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>9b2551b5-de5b-453b-ba4b-8926397a8d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>59c877b6-dd62-445f-93bb-0cdedee98d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>c58a597a-c3eb-49ab-af35-8590855a7d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>1de0d8db-35d1-40f4-b387-cd52a1654534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>127c6570-6da5-4458-8488-b808ea96a3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-10f63sf&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed css-12q0zzl&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-5l32a9&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-sizeLarge css-17vpiyo&quot;]/svg[@class=&quot;feather feather-menu&quot;]/g[1]/line[3]</value>
      <webElementGuid>3df8884d-8466-4492-bc08-1aacb83dedb0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
